# -*- coding: utf-8 -*-
"""DataType.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mthjm0sqsKKgWdeVQYCGZX3Xjz_wV_EK
"""

# basic data types
num_int = 10
num_float = 3.14
text = "python"
is_active = True

# checking data types
print("type of num_int:", type(num_int))
print("type of num_float:", type(num_float))
print("type of text:", type(text))
print("type of is_active:", type(is_active))

# arithmetic operations
sum_result = num_int + num_float
diff_result = num_int - num_float
mul_result = num_int * num_float
div_result = num_int / num_float

print("addition:", sum_result)
print("subtraction:", diff_result)
print("multiplication:", mul_result)
print("division:", div_result)

# type casting with error handling
try:
    user_input = input("enter a number: ")

    int_value = int(user_input)      # string to int
    print("integer value:", int_value)

    float_value = float(user_input)  # string to float
    print("float value:", float_value)

except ValueError:
    print("invalid number")

# string and number join
age = 21
message = "my age is " + str(age)    # int to string
print(message)


# dynamic typing example
value = 100
print("value:", value, "type:", type(value))

value = "now i am a string"
print("value:", value, "type:", type(value))

value = 45.6
print("value:", value, "type:", type(value))

